MODEL:
  TYPE: vssm
  NAME: vssm_base_a6
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 27, 2 ]
    SSM_D_STATE: 16
    SSM_DT_RANK: "auto"
    SSM_RATIO: 2.0
    SSM_FORWARDTYPE: "v05"
    MLP_RATIO: 0.0
    DOWNSAMPLE: "v1"
    PATCHEMBED: "v1"
    NORM_LAYER: "ln2d"