MODEL:
  TYPE: vssm
  NAME: vssm_tiny_aiv1
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 8, 2 ]
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 1.0
    SSM_CONV: -1
    SSM_CONV_BIAS: false
    SSM_FORWARDTYPE: "xv1a_oncnorm"
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v2"
    NORM_LAYER: "ln2d"


