MODEL:
  TYPE: vssm
  NAME: vssm_tiny_acv1_mini
  DROP_PATH_RATE: 0.0
  VSSM:
    EMBED_DIM: 192
    DEPTHS: [36]
    PATCH_SIZE: 16
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 2.0
    SSM_CONV: 3
    SSM_CONV_BIAS: false
    SSM_FORWARDTYPE: "xv1a_act"
    MLP_RATIO: 0.0
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v1"
    NORM_LAYER: "ln2d"
