MODEL:
  TYPE: vssm
  NAME: vssm_base_ahv1_0423
  DROP_PATH_RATE: 0.5
  VSSM:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 20, 2 ]
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 1.0
    SSM_CONV: -1
    SSM_CONV_BIAS: false
    SSM_FORWARDTYPE: "xv1a_ondwconv3"
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v2"
    NORM_LAYER: "ln2d"
TRAIN:
  BASE_LR: 0.001

