MODEL:
  TYPE: vssm
  NAME: vssm_tiny_a2
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 9, 2 ]
    SSM_D_STATE: 16
    SSM_DT_RANK: "auto"
    SSM_RATIO: 2.0
    SSM_FORWARDTYPE: "v04" # csm_triton + i16o32
    MLP_RATIO: 0.0
    DOWNSAMPLE: "v1"
    PATCHEMBED: "v1"